### ISSUE TITLE
Values larger than 9.9 aren't centered in the circle

### ISSUE THREAD

**Issue by Nutcake** [JoelBryceAnderson/Measure#2]
Any value that is larger than 9.9, as in three characters long, is offset to the right and not centered. 

![noncentered](https://cloud.githubusercontent.com/assets/10452593/22891890/1384497e-f211-11e6-8a59-470dfda34a88.png)

**Comment by JoelBryceAnderson** [comment]
Fixed. Thanks for the contribution!!
